[toolchain]
components = ["rustfmt", "rustc-dev"]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"

# See https://substrate.stackexchange.com/a/9069/4489
# Rust toolchain version for this workspace
#channel = "nightly-2023-08-26"
channel = "stable"

